CREATE TABLE evento_moto
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    tipo         VARCHAR(255),
    times_tamp   TIMESTAMP WITHOUT TIME ZONE,
    observacao   VARCHAR(255),
    fonte_evento VARCHAR(255),
    CONSTRAINT pk_eventomoto PRIMARY KEY (id)
);

CREATE TABLE moto
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    placa                   VARCHAR(255),
    modelo                  VARCHAR(255),
    ano                     INTEGER,
    status_moto             VARCHAR(255),
    rfid_tag                VARCHAR(255),
    data_aquisicao          date,
    ultima_manutencao       date,
    imagem_referencia       VARCHAR(255),
    caracteristicas_visuais OID,
    CONSTRAINT pk_moto PRIMARY KEY (id)
);

CREATE TABLE patio
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome      VARCHAR(255),
    endereco  VARCHAR(255),
    cidade    VARCHAR(255),
    estado    VARCHAR(255),
    pais      VARCHAR(255),
    dimensaox DOUBLE PRECISION,
    dimensaoy DOUBLE PRECISION,
    CONSTRAINT pk_patio PRIMARY KEY (id)
);

CREATE TABLE zona_patio
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    nome                VARCHAR(255),
    coordenada_inicialx DOUBLE PRECISION,
    coordenada_inicialy DOUBLE PRECISION,
    coordenada_finalx   DOUBLE PRECISION,
    coordenada_finaly   DOUBLE PRECISION,
    cor                 VARCHAR(255),
    CONSTRAINT pk_zonapatio PRIMARY KEY (id)
);