CREATE TABLE trackuser
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255),
    email      VARCHAR(255),
    avatar_url VARCHAR(255),
    CONSTRAINT pk_trackuser PRIMARY KEY (id)
);
